### ISSUE TITLE
Clickthrough as Auth?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#527] opened 2015-07-28 13:28 UTC
Should there be a specific clickthrough service that doesn't require a popup window, as no credentials are being passed around, just an accept terms and conditions sort of thing.

Wellcome has the use case, Princeton does for non-images. Anyone else?

@tomcrane to send email to iiif-discuss

**Comment by azaroth42** [comment] 2015-12-21 20:48
@tomcrane Can you document the solution to this one in an auth implementation note too? :)

**Comment by tomcrane** [comment] 2015-12-22 09:28
For the Wellcome use case we added some extra properties to drive the clickthrough user interface in the client. These properties may be a bit too Wellcome-specific for a general clickthrough solution. 

http://wellcomelibrary.org/iiif-img/b19986531-0/004f52b4-468e-4561-ad6c-f22abba4a573/info.json

This info.json has a regular login service as per the current spec, and a clickthrough service. The properties of the clickthrough service are:

|property| desc |
|---------|----|
|label|(already there) provides a title/h1 for a dialog in the UV|
|description|provides fuller explanatory text for the dialog|
|fullTerms|a link to a web page|
|fullTermsSimple|URL that returns unadorned HTML suitable for importing directly into the interface|
|actionLabel|text for the button that will trigger the clickthrough flow|

From then on it is as per regular auth flow. These terms are rather ad hoc, they essentially reproduce the user experience of the existing Wellcome Player.

As per #528, I will see what the spec looks like if clickthrough is included as an auth pattern, and try to generalise the mechanism and vocabulary.

**Comment by azaroth42** [comment] 2016-03-24 21:59
Proposal (from IIIF tech at LDCX) is for two actions:
* Add description to the auth context. If there is a description for a login service, then client SHOULD present it to the user before sending the user off to login (or otherwise get a token).
* Add a second profile clickthrough. If there is a description, then the client MUST present it to the user.

Clickthrough workflow is then just generate a token and return it -- so the auth login window will open and close straight away, as if the user had already authed.

**Comment by zimeon** [comment] 2016-09-21 13:34
I propose closing this issue, we have the Clickthrough pattern in http://iiif.io/api/auth/0.9/ at 0.9.3 live since 2016-08-22

**Comment by jpstroop** [comment] 2016-09-21 13:46
:+1:

**Comment by azaroth42** [comment] 2016-09-21 15:24
:+1:

**Comment by mikeapp** [comment] 2016-09-21 16:06
:+1:

**Comment by tomcrane** [comment] 2016-09-21 16:07
:+1:

**Closed by tomcrane** 2016-09-21 16:07 UTC
Labels: auth
