### ISSUE TITLE
Mirroring after rotation?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#963] opened 2016-10-24 11:58 UTC
@azaroth42 and I were just talking about it, and at lease when the image is rotated, mirroring a doesn't work as expected.

Rotated: https://libimages1.princeton.edu/loris/ex.jp2/3930,550,980,2630/300,/90/default.jpg

Mirrored, then rotated: https://libimages1.princeton.edu/loris/ex.jp2/3930,550,980,2630/300,/!90/default.jpg

I wouldn't expect the people in that image to appear upside down.

**Comment by jronallo** [comment] 2016-10-24 12:15
I've found mirroring with rotation to be rather confusing and I'm still not sure I've gotten it right. It would be nice to have more examples that would show what is expected for various combinations of mirroring and rotation. Without more examples I don't know that mirroring after rotation will be any easier to understand or implement.

**Comment by zimeon** [comment] 2016-10-24 12:26
Is this not already covered by the validator? I think the spec is quite clear about how it should be implemented <http://iiif.io/api/image/2.1/#rotation>: _"A leading exclamation mark (“!”) indicates that the image should be mirrored by reflection on the vertical axis before any rotation is applied."_ but agree that if there is confusion we should find a way to have better examples and/or validation.

**Comment by jronallo** [comment] 2016-10-24 12:40
The validator only tests two cases from what I can see and it is totally possible to validate on those two test cases while getting others wrong. I think my confusion in implementing this is not with the spec which is clear. I think the issue is that in order to actually get this right with tools (like ImageMagick) may require not actually following that order of operations or using different operators (flip/flop) instead of simple mirroring before rotation. Having more test cases and examples would help both implementers and the expectations of those reading the spec. Without them either order of operations will lead to confusion by some.

Validator tests:
https://github.com/IIIF/image-api/tree/master/implementations/validator/iiif_validator/tests

The two test cases that test mirroring:
https://github.com/IIIF/image-api/blob/master/implementations/validator/iiif_validator/tests/rot_mirror.py
https://github.com/IIIF/image-api/blob/master/implementations/validator/iiif_validator/tests/rot_mirror_180.py

**Comment by jpstroop** [comment] 2016-10-24 13:09
I'm wondering if the bang should come after the rotation

**Comment by zimeon** [comment] 2016-10-24 13:38
`/!90/` = `/270!/` -- one can get the same effect with either so there is only a need for one.

**Comment by jpstroop** [comment] 2016-10-24 13:41
Sure...I guess I've just been thinking that mirroring is more logical after rotation than before.

**Comment by zimeon** [comment] 2016-10-24 13:46
Discussion when we added this is in #228 (does not appear to be discussion of before vs after)

**Comment by azaroth42** [comment] 2016-10-25 08:24
I don't think there's sufficient value for the churn to change it.  There's no additional functionality enabled, as @zimeon points out.

**Comment by jpstroop** [comment] 2016-10-26 14:56
The use cases are edgy-enough as it is that I'm fine with no change--the confusion may well just be in my head.

**Comment by jpstroop** [comment] 2016-10-26 14:56
Close wontfix?

**Comment by azaroth42** [comment] 2016-10-26 15:40
:+1: to close wontfix ... doing it.

**Closed by azaroth42** 2016-10-26 15:40 UTC
Labels: wontfix
