### ISSUE TITLE
Fix CSS so that RFC words do not create extra space above and below the line

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#606] opened 2015-11-12 19:53 UTC
See, for example, <http://iiif.io/api/image/2.0/#error-conditions> where there is a single _RECOMMENDED_. Adjust window width so that this word is on the third line and you'll see extra space before and after that line compared with between first and second (normal text).

**Comment by azaroth42** [comment] 2015-11-12 21:36
Duplicate of #485. Closing that one as this description is clearer.

**Closed** 2016-09-21 11:45 UTC
Labels: website
