### ISSUE TITLE
How do I know the order of canvases and ranges in a Range?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#646] opened 2015-12-10 13:06 UTC
If I have a Range that has canvases and ranges, how do I know the order in which to display them? Some of the `canvases` may come before the `ranges` and others after.

Example: a book has covers and fly leaves at the beginning and end. I'd want to have canvases for the upper cover and front fly leaves, and then ranges for the chapters, and then more canvases for the back fly leaves and lower cover.

**Comment by azaroth42** [comment] 2015-12-12 10:27
Do we consider this in scope for 2.1?  I'm tempted to defer until 2.2 at this stage.

**Comment by jpstroop** [comment] 2015-12-12 12:50
Seems it's likely result in a breaking change , no?

**Comment by jpstroop** [comment] 2015-12-12 12:53
@tpendragon is actively developing an authoring client...curious what his thoughts are.

**Comment by tpendragon** [comment] 2015-12-15 00:45
Oh, yeah, I should comment on this:

There's no way, currently. I either have to do one of two things:

A) Create intermediate ranges with a single canvas and a meaningless label. These'll show up in the viewer and there's no hints to get them to not display.

B) The viewer we're using (universal viewer), doesn't really use range ordering for anything but the first element in the range (and I think it wouldn't even do that if you used startCanvas) - then it uses them as sets. So if the page you're on in the sequence appears in a structure, highlight the range it's in on the left. In that way, it doesn't matter - the structure controls paging, order doesn't matter, canvas labels don't show in the table of contents. It's only an issue if you want "Chapter 2a"'s canvas B to be where the viewer goes to when you click "Chapter 2", but then there's an argument that canvas B should just be in both ranges, which solves that problem.

If structures are meant to be able to be paged through one canvas at a time, then it's an issue and you need something like "elements" rather than "ranges and structures". Otherwise, I think it's fine.

**Comment by sdellis** [comment] 2015-12-15 01:28
How do you know which Sequence a Structure is referring to?  You would need this if you wanted to extract order for a Range from a Sequence, especially since a Canvas could exist in different order in multiple Sequences.

**Comment by azaroth42** [comment] 2015-12-15 14:41
@sdellis Ranges don't refer to Sequences, and the Range recursively includes all of the canvases by reference.

The order could be generated by creating a list of all canvases, recursively, in the range. Then order the canvases by the current sequence's order of canvases.

**Comment by sdellis** [comment] 2015-12-15 15:19
@azaroth42 Ok, I see.  There must always be a "current" sequence that is supplying order to the ranges.  Something still doesn't sit right with me re: this approach, but perhaps my expectations of what one can do with Ranges is inaccurate.  

Say I have, for example, a book of songs that is grouped by "Holiday Songs", "Jigs", and "Ballads" using Ranges.  Now say I want to supply an alternate grouping by geographical origin, say "Irish Songs", "Scottish Songs", and "German Songs" and alphabetize them (or create some other order) within those groups.  If I understand you correctly, I would have to create a separate Sequence to give me the alternate order based on the constraints of my alternate grouping.  In that sense, the alternate Sequence must know about the Range's groupings before it can create any order.  That requires tighter coupling than is possible with the Prezi API since there's no reference between grouping (ranges) and order (sequences).  How do I know which Range is intended/preferred for a given Sequence?

**Comment by azaroth42** [comment] 2015-12-15 15:34
That can be done with the current model. The issue is about the ordering of the canvases when a range contains both ranges and canvases.

For the songs example you could create one range per song, and then one range per grouping. The grouping ranges include the song ranges.

**Comment by sdellis** [comment] 2015-12-15 16:13
Ok, gotcha. However, for the songs example, I still can't determine (from the data) which sequence contains the preferred canvas order for the alternate structure of the song book.

**Comment by jpstroop** [comment] 2015-12-15 16:25
@sdellis The way I would approach your use case is to have one sequence that reflects the physical order, and then multiple ranges for the the the different orders in which you want to place the songs. In `structures` you'd define the range for each song once, and you'd have two ranges with `"viewingHint" : "top"`. One would have the label, e.g., "Contents" and list the ranges in the physical order, and the other would have the label, e.g. "Songs by Region" and reference those same ranges in different order, probably with additional intermediate structure, i.e. ranges for each region.

**Comment by tpendragon** [comment] 2015-12-15 17:30
> The issue is about the ordering of the canvases when a range contains both ranges and canvases.

Which is only a problem if you need to be able to iterate through the canvases referenced by ranges, yes? The only use case I see for that is probably things like newspapers, where the order created by the ranges (which are allowed to reference parts of pages) is importantly different from that of the sequence - but I haven't kept up with that, you've probably dealt with it somehow.

**Comment by tpendragon** [comment] 2015-12-15 17:32
> Ok, gotcha. However, for the songs example, I still can't determine (from the data) which sequence contains the preferred canvas order for the alternate structure of the song book.

I think the answer is "if the order you flip through the pages is important, you need a new sequence." I don't think structures need to be associated with sequences, because canvases are parts of structures independent of what their order is.

**Comment by sdellis** [comment] 2015-12-15 17:34
Ok, so BOTH sequences AND structures can specify order.  That was what was not clear to me as the API doesn't explicitly state that structures provide order, and I can see that's where the rub is in this issue, *when canvases are not represented in Ranges, but should appear in a certain sequence in a paged viewing order*. It seems to me that sometimes you want two types of navigation (particularly, as @tpendragon mentioned, in newspapers), one where you can jump to the startCanvas of a range and page through in sequential order, and one where you jump to the startCanvas and navigate to the next canvas in the Range (also the case in the song grouping example). The preferred navigation may change based on the context.

**Comment by azaroth42** [comment] 2015-12-18 00:24
Tagging defer as there's no non-breaking change possible.

**Comment by azaroth42** [comment] 2015-12-18 20:59
Duplicate of #58, I think.

**Comment by aeschylus** [comment] 2015-12-18 21:14
I agree that Shaun's problem is #58. It seems my [proposition](https://github.com/IIIF/iiif.io/issues/58#issuecomment-42859824) has been fulfilled in the case of newspapers. Maybe this issue ( #646 ) is a duplicate, since I didn't think the canvases were meant to be displayed from ranges, but only to specify which canvases the range references.

It's also true for palimpsests.

Another poignant phrase has emerged from this discussion: "The preferred navigation may change based on the context."

**Comment by jpstroop** [comment] 2016-02-03 22:39
This is the same as #697 (just swap Collection for Range). Propose added `members` to each for a consistent solution.

**Comment by sdellis** [comment] 2016-02-05 04:24
@jpstroop: they are similar, but there are a few key differences between this case and #697. One difference is that you only have URIs of canvases, which makes it a bit harder to tell the difference between what is a range and what is a canvas in the members list.  There are several ways to resolve this, though none seem great:  I imagine you have to do a lookup in both the sequence and structure to figure out what it is?  That would be better than doing an external http request for every member.  Or I suppose @type could be included in the ```members``` list which duplicates some canvas and range  information. 

I also contend that there is nothing consistent about ```members``` except for the property label that's used.  In fact, the member resources can be completely inconsistent in the sense that they could be anything, except that context alone determines what is a valid "member".  Again, I feel this adds unnecessary ambiguity and complexity to the developer experience and does not follow the intent to keep the spec as simple as possible.

**Comment by sdellis** [comment] 2016-02-05 04:34
That said, the I don't have a non-breaking alternative proposal as in #697. The only alternative solution I have to propose is that a range can either have ranges or canvases, but not both.

**Comment by jpstroop** [comment] 2016-02-05 13:57
> Or I suppose @type could be included in the members list

Yes. I was talking about this with @azaroth42 earlier in the week, and I think we agreed that if `members` stands each member of the list would need `@type`, `@id`, and `label`.

**Comment by azaroth42** [comment] 2016-03-04 22:29
Closed by #738

**Closed by azaroth42** 2016-03-04 22:29 UTC
Labels: defer, presentation, Ready
