### ISSUE TITLE
Presentation API section 1.1 should now refer to Search API

### ISSUE THREAD

**Issue by tomcramer** [IIIF/iiif.io#956] opened 2016-10-18 01:26 UTC
Section 1.1, Scope currently reads "Search within the object is not supported by the Presentation API; **however this will be covered by a future IIIF specification.**"; this latter part can be updated with a link to Search API now, no?

**Comment by zimeon** [comment] 2016-10-18 01:50
Yes, but dupe of #948

**Closed by zimeon** 2016-10-18 01:50 UTC
