### ISSUE TITLE
[OSD] Reports of IIIF not working in OSD 2.0

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#563] opened 2015-10-03 17:39 UTC
Confirm or deny.  If confirmed, then we should contribute to a fix.

**Comment by jronallo** [comment] 2015-10-06 01:00
I had problems using OSD 2.0.

**Comment by jpstroop** [comment] 2015-10-06 01:08
Yup, this came from you. Could you reiterate what you told me if you have a
sec?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by aeschylus** [comment] 2015-10-06 01:21
Also interested in this, and doubtful. Seems to work fine to me. Could it be another info.json/running service mismatch? Most of the time this comes up, the info.json says one thing while the actual server expects something else ("native" vs. "default" .jpg).

**Comment by zimeon** [comment] 2015-10-06 02:55
I have not seen any problems with OSD 2.0.0 when I was working with the auth demo for OR15. Also, I have the static file demo at <https://github.com/zimeon/iiif/tree/master/demo-static> working on OSD 2.0.

@jronallo - can you give us a recipe to repeat the problem?

**Comment by sdellis** [comment] 2015-10-06 12:21
I don't know if this is relevant, but just today I was trying to debug an
issue with OSD 2.0 and Loris and Safari.  Previously, I was using the Image
API 1.0 and building the constructor's tileSources property based on what
was available in the info.json response.  When I switched to 2.0, something
broke with the tileSources value I was previously using (there were not
really many good examples for 2.0) and discovered that I could simply set
the profile value to the image URI and it seemed like OSD was able to
figure it out.

However, now I'm having a problem with Loris and the headers that Safari is
sending <http://transcribe.princeton.edu/scripto/transcribe/25/3879> (bare
essentials code in this jsbin
<http://jsbin.com/cagenideka/1/edit?html,js,output> -- for some reason the
image is not rendering, but you only get errors in Safari):

XMLHttpRequest cannot load
http://libimages.princeton.edu/loris2/pudl0017%2Fc1357%2F6005617%2F001%2F01%2F00000002.jp2/info.json.
Request header field Accept-Encoding is not allowed by
Access-Control-Allow-Headers.
openseadragon.min.js:6:15130AJAX request returned :
http://libimages.princeton.edu/loris2/pudl0017/c1357/6005617/001/01/00000002.jp2


Here are the headers Safari's sending:

```Access-Control-Request-Headers    accept-language, origin, accept-encoding


Perhaps it's unrelated to Jason's problem, but seemed like it could be
relevant.

-Shaun

On Mon, Oct 5, 2015 at 9:21 PM, aeschylus <notifications@github.com> wrote:

> Also interested in this, and doubtful. Seems to work fine to me. Could it
> be another info.json/running service mismatch? Most of the time this comes
> up, the info.json says one thing while the actual server expects something
> else ("native" vs. "default" .jpg).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/iiif.io/issues/563#issuecomment-145717523>.
>

**Comment by jronallo** [comment] 2015-10-06 12:51
To reproduce the problem I was experiencing install Loris and the Loris OSD demo like here:
https://github.com/jronallo/loris-vagrant-centos7-install

At this point OSD should work. Then upgrade OSD to 2.0 and I experience an issue with zooming. It is as if not all the levels are being seen. Instead of having 6 or so zoom levels, I can zoom in about 3 times, but then I can only zoom back out once or twice.

The example here using OSD 2.0.0 exhibits something similar to what I was experiencing where it seems as if not all the possible zoom levels are available. There might be some other issues with this demo as well since looking at the tiles that get returned they seem to be from multiple images.
https://openseadragon.github.io/examples/tilesource-iiif/

So maybe some of the configuration options have changed in OSD 2.0 but since I didn't make those changes that's why I'm seeing issues? Does anyone have a demo of Loris with OSD so that I can inspect any code differences?

**Comment by jpstroop** [comment] 2015-10-06 14:45
As an aside, the IIIF demo page on the OSd is woefully out of date. 
Working up a PR now.

**Comment by jpstroop** [comment] 2015-10-06 14:58
FYI: openseadragon/openseadragon.github.com#11

**Comment by jpstroop** [comment] 2015-10-14 17:51
The OpenSeadragon demo site is now using the latest everything:

http://openseadragon.github.io/examples/tilesource-iiif/

**Comment by jpstroop** [comment] 2015-10-21 20:51
I'm not seeing any problems there. Closing.

**Closed by jpstroop** 2015-10-21 20:51 UTC
Labels: image
